import type { TicketStatus, Priority, Channel } from "@/lib/types"

export type DemoCustomer = {
  id: string
  name: string
  email: string
  company: string
}

export type DemoTicket = {
  id: string
  ticketNumber: number
  subject: string
  description: string
  status: TicketStatus
  priority: Priority
  channel: Channel
  tags: string[]
  createdAt: Date
  resolvedAt?: Date
  customer: DemoCustomer
  assignedAgent: { id: string; name: string; avatarUrl: null } | null
  _count: { messages: number }
  aiSuggestedResponse?: string
  aiAnalyzedAt?: Date
}

const now = Date.now()
const daysAgo = (d: number) => new Date(now - d * 86_400_000)
const hoursAgo = (h: number) => new Date(now - h * 3_600_000)

export const DEMO_CUSTOMERS: DemoCustomer[] = [
  { id: "c1", name: "Priya Mehra",    email: "priya@acmecorp.io",      company: "Acme Corp" },
  { id: "c2", name: "Carlos Rivas",   email: "c.rivas@globex.com",     company: "Globex" },
  { id: "c3", name: "Hannah Park",    email: "hannah@stellar.dev",     company: "Stellar Dev" },
  { id: "c4", name: "James Okafor",   email: "j.okafor@veridian.co",   company: "Veridian" },
  { id: "c5", name: "Amelia Torres",  email: "amelia@brightwave.io",   company: "Brightwave" },
  { id: "c6", name: "Noah Chen",      email: "n.chen@peaklabs.io",     company: "Peak Labs" },
  { id: "c7", name: "Sofia Andersen", email: "sofia@nordic-saas.dk",   company: "Nordic SaaS" },
  { id: "c8", name: "Ethan Patel",    email: "ethan@vaultworks.com",   company: "VaultWorks" },
  { id: "c9", name: "Lena Müller",    email: "l.mueller@finvest.de",   company: "Finvest GmbH" },
  { id: "c10", name: "Marcus Webb",   email: "m.webb@looplabs.com",    company: "Loop Labs" },
]

const AI_RESPONSE = (subject: string) =>
  `Thank you for reaching out about "${subject}". I've reviewed the details and escalated this to the appropriate team. We'll follow up within our agreed SLA window. In the meantime, please let us know if anything changes on your end.`

export const DEMO_TICKETS: DemoTicket[] = [
  // ── CRITICAL ────────────────────────────────────────────────────────────
  {
    id: "t1", ticketNumber: 1,
    subject: "Production API returning 503 for all enterprise accounts",
    description: "Since 14:30 UTC today every request to /api/v2/orders returns HTTP 503. Enterprise clients are impacted and we're losing ~$4k/minute. Needs immediate triage.",
    status: "IN_PROGRESS", priority: "CRITICAL", channel: "EMAIL",
    tags: ["api", "production", "critical-incident"],
    createdAt: hoursAgo(2), customer: DEMO_CUSTOMERS[0],
    assignedAgent: { id: "agent-1", name: "Alex Kim", avatarUrl: null },
    _count: { messages: 8 },
    aiSuggestedResponse: AI_RESPONSE("Production API returning 503 for all enterprise accounts"),
    aiAnalyzedAt: hoursAgo(1.5),
  },
  {
    id: "t2", ticketNumber: 2,
    subject: "Data export contains rows from a different tenant — possible breach",
    description: "I downloaded our monthly CSV export and rows 500–600 contain customer records from a completely different organisation. This is a serious data issue requiring immediate attention.",
    status: "OPEN", priority: "CRITICAL", channel: "EMAIL",
    tags: ["security", "data-leak", "urgent"],
    createdAt: daysAgo(1), customer: DEMO_CUSTOMERS[3],
    assignedAgent: null, _count: { messages: 3 },
    aiSuggestedResponse: AI_RESPONSE("Data export contains rows from a different tenant"),
    aiAnalyzedAt: daysAgo(1),
  },
  {
    id: "t3", ticketNumber: 3,
    subject: "Payment processing completely down — checkout failing for all users",
    description: "Our checkout flow has been broken for the past 45 minutes. Stripe webhooks are timing out and no payments are completing. This is our peak sales window.",
    status: "IN_PROGRESS", priority: "CRITICAL", channel: "CHAT",
    tags: ["payments", "stripe", "production"],
    createdAt: hoursAgo(1), customer: DEMO_CUSTOMERS[5],
    assignedAgent: { id: "agent-1", name: "Alex Kim", avatarUrl: null },
    _count: { messages: 12 },
    aiSuggestedResponse: AI_RESPONSE("Payment processing completely down"),
    aiAnalyzedAt: hoursAgo(0.5),
  },
  {
    id: "t4", ticketNumber: 4,
    subject: "Database replication lag causing stale reads in reporting module",
    description: "Our analytics dashboard is showing data from 6+ hours ago. The replication lag alarm has been firing since yesterday. Finance team cannot run their end-of-month reports.",
    status: "OPEN", priority: "CRITICAL", channel: "API",
    tags: ["database", "replication", "reporting"],
    createdAt: daysAgo(1), customer: DEMO_CUSTOMERS[8],
    assignedAgent: null, _count: { messages: 5 },
  },
  // ── HIGH ────────────────────────────────────────────────────────────────
  {
    id: "t5", ticketNumber: 5,
    subject: "Billing portal not reflecting payment made 3 days ago",
    description: "We transferred $12,400 on the 18th and the dashboard still shows the balance as outstanding. Our CFO needs urgent clarification before end of day.",
    status: "OPEN", priority: "HIGH", channel: "EMAIL",
    tags: ["billing", "payment"],
    createdAt: daysAgo(1), customer: DEMO_CUSTOMERS[1],
    assignedAgent: null, _count: { messages: 2 },
    aiSuggestedResponse: AI_RESPONSE("Billing portal not reflecting payment made 3 days ago"),
    aiAnalyzedAt: daysAgo(1),
  },
  {
    id: "t6", ticketNumber: 6,
    subject: "SSO broken after maintenance window — entire team locked out",
    description: "Since last night's maintenance window our SAML SSO integration is broken. All 47 agents are locked out. We have a 9 AM stand-up in 2 hours — this is blocking everyone.",
    status: "IN_PROGRESS", priority: "HIGH", channel: "CHAT",
    tags: ["sso", "auth", "maintenance"],
    createdAt: daysAgo(2), customer: DEMO_CUSTOMERS[2],
    assignedAgent: { id: "agent-1", name: "Alex Kim", avatarUrl: null },
    _count: { messages: 9 },
    aiSuggestedResponse: AI_RESPONSE("SSO broken after maintenance window"),
    aiAnalyzedAt: daysAgo(2),
  },
  {
    id: "t7", ticketNumber: 7,
    subject: "Webhook signature verification fails on all events",
    description: "Starting yesterday our webhook endpoint rejects every event because signature verification fails. We haven't changed our secret — suspect your signing key was rotated without notice.",
    status: "WAITING_ON_CUSTOMER", priority: "HIGH", channel: "API",
    tags: ["webhooks", "manual-review"],
    createdAt: daysAgo(3), customer: DEMO_CUSTOMERS[4],
    assignedAgent: { id: "agent-1", name: "Alex Kim", avatarUrl: null },
    _count: { messages: 6 },
  },
  {
    id: "t8", ticketNumber: 8,
    subject: "Mobile app crashes on iOS 17.4 immediately after login",
    description: "Since updating to iOS 17.4 the app crashes within 2 seconds of logging in. Affects all of our field agents on iPhones. Android is fine. Crash log attached.",
    status: "IN_PROGRESS", priority: "HIGH", channel: "EMAIL",
    tags: ["mobile", "ios", "crash"],
    createdAt: daysAgo(2), customer: DEMO_CUSTOMERS[6],
    assignedAgent: { id: "agent-1", name: "Alex Kim", avatarUrl: null },
    _count: { messages: 7 },
    aiSuggestedResponse: AI_RESPONSE("Mobile app crashes on iOS 17.4 immediately after login"),
    aiAnalyzedAt: daysAgo(2),
  },
  {
    id: "t9", ticketNumber: 9,
    subject: "Enterprise SSO token expiry too short — forcing re-auth every 15 min",
    description: "Our security team configured SSO but the session token expires every 15 minutes. This is causing constant interruptions for our users. We need this extended to at least 8 hours.",
    status: "OPEN", priority: "HIGH", channel: "EMAIL",
    tags: ["sso", "session", "enterprise"],
    createdAt: daysAgo(3), customer: DEMO_CUSTOMERS[9],
    assignedAgent: null, _count: { messages: 4 },
    aiSuggestedResponse: AI_RESPONSE("Enterprise SSO token expiry too short"),
    aiAnalyzedAt: daysAgo(3),
  },
  {
    id: "t10", ticketNumber: 10,
    subject: "Bulk user import fails silently at 500+ rows",
    description: "When importing more than 500 users via CSV the UI shows 'Import complete' but only the first 499 rows are created. No error shown. We need to onboard 2,000 users this week.",
    status: "WAITING_ON_CUSTOMER", priority: "HIGH", channel: "EMAIL",
    tags: ["import", "bug", "enterprise"],
    createdAt: daysAgo(4), customer: DEMO_CUSTOMERS[7],
    assignedAgent: { id: "agent-1", name: "Alex Kim", avatarUrl: null },
    _count: { messages: 5 },
  },
  // ── MEDIUM ──────────────────────────────────────────────────────────────
  {
    id: "t11", ticketNumber: 11,
    subject: "Analytics charts blank on Safari 16 — affecting weekly reporting",
    description: "The Reports page charts are completely blank for all Safari users on our team. Chrome and Firefox work fine. Blocking our weekly executive reporting workflow.",
    status: "OPEN", priority: "MEDIUM", channel: "EMAIL",
    tags: ["browser-compat", "charts"],
    createdAt: daysAgo(2), customer: DEMO_CUSTOMERS[0],
    assignedAgent: null, _count: { messages: 2 },
    aiSuggestedResponse: AI_RESPONSE("Analytics charts blank on Safari 16"),
    aiAnalyzedAt: daysAgo(2),
  },
  {
    id: "t12", ticketNumber: 12,
    subject: "How do I configure custom roles for our enterprise plan?",
    description: "I'm the workspace admin and want to set up custom permission roles but can't find the setting. We're on the Enterprise plan. Can you guide me through the configuration?",
    status: "RESOLVED", priority: "MEDIUM", channel: "CHAT",
    tags: ["roles", "permissions", "how-to"],
    createdAt: daysAgo(3), resolvedAt: daysAgo(2),
    customer: DEMO_CUSTOMERS[1], assignedAgent: null, _count: { messages: 4 },
    aiSuggestedResponse: AI_RESPONSE("How do I configure custom roles"),
    aiAnalyzedAt: daysAgo(3),
  },
  {
    id: "t13", ticketNumber: 13,
    subject: "Need consolidated Q1 invoice with line items for finance team",
    description: "Finance needs a single invoice covering January–March with individual line items for each subscription tier. Can you generate that and send it to billing@veridian.co?",
    status: "RESOLVED", priority: "MEDIUM", channel: "EMAIL",
    tags: ["billing", "invoice"],
    createdAt: daysAgo(4), resolvedAt: daysAgo(3),
    customer: DEMO_CUSTOMERS[3], assignedAgent: null, _count: { messages: 3 },
    aiSuggestedResponse: AI_RESPONSE("Consolidated Q1 invoice with line items"),
    aiAnalyzedAt: daysAgo(4),
  },
  {
    id: "t14", ticketNumber: 14,
    subject: "API rate limit docs contradict actual behaviour — 429s at 200 req/min",
    description: "Your docs state the limit is 1000 req/min but we're hitting 429s at ~200 req/min consistently. Either the docs are wrong or there's a bug.",
    status: "IN_PROGRESS", priority: "MEDIUM", channel: "EMAIL",
    tags: ["api", "documentation", "rate-limit"],
    createdAt: daysAgo(4), customer: DEMO_CUSTOMERS[2],
    assignedAgent: { id: "agent-1", name: "Alex Kim", avatarUrl: null },
    _count: { messages: 6 },
  },
  {
    id: "t15", ticketNumber: 15,
    subject: "Import silently fails on files over 50 MB with no error message",
    description: "When I try to import a 78 MB CSV the UI spins forever then resets — no error shown. Smaller files work fine. Is there a documented limit I'm not aware of?",
    status: "OPEN", priority: "MEDIUM", channel: "EMAIL",
    tags: ["import", "bug"],
    createdAt: daysAgo(5), customer: DEMO_CUSTOMERS[4],
    assignedAgent: null, _count: { messages: 1 },
    aiSuggestedResponse: AI_RESPONSE("Import silently fails on files over 50 MB"),
    aiAnalyzedAt: daysAgo(5),
  },
  {
    id: "t16", ticketNumber: 16,
    subject: "Slack integration stopped posting ticket notifications — no errors",
    description: "We connected Slack two weeks ago and it worked great. Since Monday all notifications stopped. The integration shows 'Connected' in settings but nothing posts to the channel.",
    status: "OPEN", priority: "MEDIUM", channel: "SOCIAL",
    tags: ["integrations", "slack"],
    createdAt: daysAgo(5), customer: DEMO_CUSTOMERS[0],
    assignedAgent: null, _count: { messages: 3 },
    aiSuggestedResponse: AI_RESPONSE("Slack integration stopped posting ticket notifications"),
    aiAnalyzedAt: daysAgo(5),
  },
  {
    id: "t17", ticketNumber: 17,
    subject: "Two-factor authentication codes not arriving via SMS",
    description: "Several of our users in the APAC region are not receiving 2FA SMS codes. Email-based 2FA works fine. This affects ~20 users across Singapore and Australia offices.",
    status: "WAITING_ON_CUSTOMER", priority: "MEDIUM", channel: "EMAIL",
    tags: ["auth", "2fa", "sms"],
    createdAt: daysAgo(3), customer: DEMO_CUSTOMERS[5],
    assignedAgent: { id: "agent-1", name: "Alex Kim", avatarUrl: null },
    _count: { messages: 5 },
    aiSuggestedResponse: AI_RESPONSE("Two-factor authentication codes not arriving via SMS"),
    aiAnalyzedAt: daysAgo(3),
  },
  {
    id: "t18", ticketNumber: 18,
    subject: "Custom domain setup — SSL certificate not propagating",
    description: "We set up a custom domain 48 hours ago following your guide but the SSL cert still shows as invalid in browsers. DNS records are correct. Could be a cert provisioning issue on your end.",
    status: "IN_PROGRESS", priority: "MEDIUM", channel: "CHAT",
    tags: ["domain", "ssl", "setup"],
    createdAt: daysAgo(2), customer: DEMO_CUSTOMERS[6],
    assignedAgent: { id: "agent-1", name: "Alex Kim", avatarUrl: null },
    _count: { messages: 7 },
    aiSuggestedResponse: AI_RESPONSE("Custom domain setup — SSL certificate not propagating"),
    aiAnalyzedAt: daysAgo(2),
  },
  {
    id: "t19", ticketNumber: 19,
    subject: "Reports export to PDF cuts off last column on landscape layout",
    description: "When exporting any report to PDF in landscape mode the rightmost column is clipped. Portrait mode is fine. This is blocking our monthly client presentations.",
    status: "RESOLVED", priority: "MEDIUM", channel: "EMAIL",
    tags: ["reports", "pdf", "export"],
    createdAt: daysAgo(6), resolvedAt: daysAgo(4),
    customer: DEMO_CUSTOMERS[8], assignedAgent: null, _count: { messages: 4 },
    aiSuggestedResponse: AI_RESPONSE("Reports export to PDF cuts off last column"),
    aiAnalyzedAt: daysAgo(6),
  },
  {
    id: "t20", ticketNumber: 20,
    subject: "Search returning results from archived records — needs scope filter",
    description: "The global search includes archived tickets and customers in results, making it hard to find active records. We need a way to exclude archived items or scope the search.",
    status: "OPEN", priority: "MEDIUM", channel: "EMAIL",
    tags: ["search", "feature-request"],
    createdAt: daysAgo(7), customer: DEMO_CUSTOMERS[9],
    assignedAgent: null, _count: { messages: 2 },
  },
  // ── LOW ────────────────────────────────────────────────────────────────
  {
    id: "t21", ticketNumber: 21,
    subject: "Date picker resets to '7 days' on every page visit — please persist",
    description: "Small UX request: every time I navigate to Reports the date range resets to 'last 7 days'. I always use 30 days — it would be great if the preference persisted.",
    status: "RESOLVED", priority: "LOW", channel: "EMAIL",
    tags: ["feature-request", "ux"],
    createdAt: daysAgo(5), resolvedAt: daysAgo(4),
    customer: DEMO_CUSTOMERS[1], assignedAgent: null, _count: { messages: 2 },
    aiSuggestedResponse: AI_RESPONSE("Date picker resets on every page visit"),
    aiAnalyzedAt: daysAgo(5),
  },
  {
    id: "t22", ticketNumber: 22,
    subject: "Typo on Settings page — 'Notificaitons'",
    description: "Minor but: the Settings > Notifications tab heading reads 'Notificaitons'. Just flagging it so it gets cleaned up in the next release.",
    status: "CLOSED", priority: "LOW", channel: "EMAIL",
    tags: ["typo", "ui"],
    createdAt: daysAgo(6), resolvedAt: daysAgo(5),
    customer: DEMO_CUSTOMERS[3], assignedAgent: null, _count: { messages: 1 },
    aiSuggestedResponse: AI_RESPONSE("Typo on Settings page"),
    aiAnalyzedAt: daysAgo(6),
  },
  {
    id: "t23", ticketNumber: 23,
    subject: "Dark mode request for agent dashboard — late-shift eye strain",
    description: "Our agents work late shifts and the bright white dashboard causes significant eye strain. A dark mode toggle would make a big difference. Is this on the roadmap?",
    status: "CLOSED", priority: "LOW", channel: "EMAIL",
    tags: ["feature-request", "dark-mode"],
    createdAt: daysAgo(6), resolvedAt: daysAgo(5),
    customer: DEMO_CUSTOMERS[2], assignedAgent: null, _count: { messages: 3 },
  },
  {
    id: "t24", ticketNumber: 24,
    subject: "Where can I find your SLA and uptime history for procurement review?",
    description: "We're going through a procurement review and legal needs your SLA document plus recent uptime history. Can you point me to the right resources or attach them here?",
    status: "RESOLVED", priority: "LOW", channel: "EMAIL",
    tags: ["sla", "compliance"],
    createdAt: daysAgo(6), resolvedAt: daysAgo(5),
    customer: DEMO_CUSTOMERS[4], assignedAgent: null, _count: { messages: 2 },
    aiSuggestedResponse: AI_RESPONSE("SLA and uptime history for procurement review"),
    aiAnalyzedAt: daysAgo(6),
  },
  {
    id: "t25", ticketNumber: 25,
    subject: "Can we get a sandbox environment for our integration testing?",
    description: "Our dev team wants to test the API integration without affecting live data. Do you offer a sandbox or staging environment we can use for QA?",
    status: "CLOSED", priority: "LOW", channel: "CHAT",
    tags: ["sandbox", "api", "feature-request"],
    createdAt: daysAgo(7), resolvedAt: daysAgo(6),
    customer: DEMO_CUSTOMERS[7], assignedAgent: null, _count: { messages: 4 },
    aiSuggestedResponse: AI_RESPONSE("Sandbox environment for integration testing"),
    aiAnalyzedAt: daysAgo(7),
  },
  {
    id: "t26", ticketNumber: 26,
    subject: "Notification emails going to spam for Gmail users",
    description: "Several users on our team using Gmail are finding ticket notification emails in their spam folder. SPF and DKIM should be configured — can you verify your sending domain setup?",
    status: "CLOSED", priority: "LOW", channel: "EMAIL",
    tags: ["email", "spam", "deliverability"],
    createdAt: daysAgo(8), resolvedAt: daysAgo(7),
    customer: DEMO_CUSTOMERS[6], assignedAgent: null, _count: { messages: 3 },
    aiSuggestedResponse: AI_RESPONSE("Notification emails going to spam"),
    aiAnalyzedAt: daysAgo(8),
  },
  {
    id: "t27", ticketNumber: 27,
    subject: "Add keyboard shortcut to quickly create a new ticket",
    description: "Power user request: it would be great to have a keyboard shortcut (e.g. Cmd+K or N) to open the new ticket dialog without reaching for the mouse. Would save our agents a lot of time.",
    status: "OPEN", priority: "LOW", channel: "CHAT",
    tags: ["keyboard", "ux", "feature-request"],
    createdAt: daysAgo(9), customer: DEMO_CUSTOMERS[9],
    assignedAgent: null, _count: { messages: 1 },
    aiSuggestedResponse: AI_RESPONSE("Add keyboard shortcut to quickly create a new ticket"),
    aiAnalyzedAt: daysAgo(9),
  },
  {
    id: "t28", ticketNumber: 28,
    subject: "Timezone discrepancy in ticket timestamps — shows UTC instead of local",
    description: "All ticket timestamps display in UTC. Our team is spread across 4 timezones and it's causing confusion when discussing ticket timelines. Can timestamps display in the user's local timezone?",
    status: "RESOLVED", priority: "LOW", channel: "EMAIL",
    tags: ["timezone", "ux"],
    createdAt: daysAgo(10), resolvedAt: daysAgo(8),
    customer: DEMO_CUSTOMERS[0], assignedAgent: null, _count: { messages: 3 },
    aiSuggestedResponse: AI_RESPONSE("Timezone discrepancy in ticket timestamps"),
    aiAnalyzedAt: daysAgo(10),
  },
  {
    id: "t29", ticketNumber: 29,
    subject: "CSV export includes hidden columns — extra blank columns in output",
    description: "When exporting the ticket list to CSV there are 3–4 blank columns that don't correspond to any visible table column. Seems like hidden metadata fields are being included.",
    status: "CLOSED", priority: "LOW", channel: "EMAIL",
    tags: ["export", "csv", "bug"],
    createdAt: daysAgo(11), resolvedAt: daysAgo(9),
    customer: DEMO_CUSTOMERS[8], assignedAgent: null, _count: { messages: 2 },
    aiSuggestedResponse: AI_RESPONSE("CSV export includes hidden columns"),
    aiAnalyzedAt: daysAgo(11),
  },
  {
    id: "t30", ticketNumber: 30,
    subject: "Request to add Portuguese (Brazil) language support",
    description: "We're expanding our operations to Brazil and our new team members need the UI in Portuguese. Do you have a localisation roadmap? Is there a way to contribute translations?",
    status: "OPEN", priority: "LOW", channel: "EMAIL",
    tags: ["i18n", "feature-request"],
    createdAt: daysAgo(12), customer: DEMO_CUSTOMERS[5],
    assignedAgent: null, _count: { messages: 1 },
    aiSuggestedResponse: AI_RESPONSE("Portuguese (Brazil) language support"),
    aiAnalyzedAt: daysAgo(12),
  },
]
