import { PrismaClient, TicketStatus, Priority, Channel, Role, Plan } from "@prisma/client"
import { PrismaPg } from "@prisma/adapter-pg"
import pg from "pg"

const pool = new pg.Pool({ connectionString: process.env.DATABASE_URL })
const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! })
const prisma = new PrismaClient({ adapter })

// ─────────────────────────────────────────────────────────────
// SEED DATA
// ─────────────────────────────────────────────────────────────

async function main() {
  console.log("🌱 Starting Heiyo-Connect seed...")
  console.log("   Clearing existing seed data...")

  // Clean up in reverse FK order
  await prisma.message.deleteMany()
  await prisma.ticket.deleteMany()
  await prisma.customer.deleteMany()
  await prisma.apiKey.deleteMany()
  await prisma.user.deleteMany()
  await prisma.tenant.deleteMany()

  // ── TENANT 1: Aura Logistics (DEMO TENANT) ──────────────────
  console.log("   Creating Aura Logistics (demo tenant)...")
  const aura = await prisma.tenant.create({
    data: {
      name: "Aura Logistics",
      slug: "aura-logistics",
      plan: Plan.PRO,
    },
  })

  const demoClerkId = process.env.DEMO_CLERK_USER_ID ?? "demo_clerk_placeholder_set_env_var"

  const auraAgent = await prisma.user.create({
    data: {
      clerkId: demoClerkId,
      email: "demo@aura-logistics.com",
      name: "Alex Rivera",
      role: Role.OWNER,
      tenantId: aura.id,
    },
  })

  const auraCustomers = await Promise.all([
    prisma.customer.create({ data: { tenantId: aura.id, email: "marcus@shippingco.com", name: "Marcus Chen", phone: "+1-415-555-0192" } }),
    prisma.customer.create({ data: { tenantId: aura.id, email: "priya@nair-exports.com", name: "Priya Nair", phone: "+91-98200-44321" } }),
    prisma.customer.create({ data: { tenantId: aura.id, email: "jordan@blakefreight.com", name: "Jordan Blake" } }),
    prisma.customer.create({ data: { tenantId: aura.id, email: "amara@westafricatrade.com", name: "Amara Osei", phone: "+233-302-555-0178" } }),
    prisma.customer.create({ data: { tenantId: aura.id, email: "lena@muellerhauling.de", name: "Lena Mueller" } }),
  ])

  const [marcus, priya, jordan, amara, lena] = auraCustomers

  const auraTickets = [
    {
      subject: "Shipment delayed in Singapore port — urgent",
      description: "Our container (MSKU-4891023) has been held at PSA Singapore for 6 days with no clearance update. Our downstream client has a hard deadline in 48 hours. We need immediate escalation to the port authority and a new ETA.",
      status: TicketStatus.OPEN,
      priority: Priority.CRITICAL,
      channel: Channel.EMAIL,
      tags: ["logistics", "port-delay", "escalation"],
      aiSuggestedResponse: "Dear Marcus, I've raised an urgent escalation ticket with our PSA Singapore liaison (Ref: PSA-ESC-2291). Initial review indicates a documentation discrepancy on the Bill of Lading — specifically a mismatch in the shipper's address code. I recommend issuing an amended B/L immediately via your freight forwarder. Our team will follow up with the port within 4 hours and provide a revised ETA. We sincerely apologize for the impact on your downstream commitments.",
      aiPriority: Priority.CRITICAL,
      aiAnalyzedAt: new Date(Date.now() - 1000 * 60 * 30),
      customerId: marcus.id,
      assignedAgentId: auraAgent.id,
    },
    {
      subject: "Invoice mismatch on Order #AL-4892",
      description: "The invoice issued for Order #AL-4892 shows $14,820 but our PO was approved for $13,200. The discrepancy of $1,620 appears to be a fuel surcharge that was not included in the original quote. Please clarify and reissue.",
      status: TicketStatus.IN_PROGRESS,
      priority: Priority.HIGH,
      channel: Channel.EMAIL,
      tags: ["billing", "invoice", "dispute"],
      aiSuggestedResponse: "Hello Priya, I've reviewed Order #AL-4892 against your approved PO (PO-2024-0318). The $1,620 difference is a Q1 fuel surcharge adjustment (FSA-Q1-2025) that was communicated via our rate update notice in January. I'll have our billing team send you the full rate sheet breakdown and an itemised invoice within 2 business hours. If the surcharge was not in your contract scope, we will issue a credit note for the difference.",
      aiPriority: Priority.HIGH,
      aiAnalyzedAt: new Date(Date.now() - 1000 * 60 * 90),
      customerId: priya.id,
      assignedAgentId: auraAgent.id,
    },
    {
      subject: "Driver GPS tracker not updating — 3 vehicles affected",
      description: "GPS units on vehicles AU-112, AU-119, and AU-127 stopped updating at 14:30 UTC today. Dispatcher cannot confirm vehicle positions. Fleet is currently in transit on Route R-47 (Melbourne → Brisbane). Need immediate resolution.",
      status: TicketStatus.OPEN,
      priority: Priority.HIGH,
      channel: Channel.CHAT,
      tags: ["fleet", "gps", "tracking"],
      aiSuggestedResponse: "Hi Jordan, our telematics team has identified a firmware sync failure affecting the Trimble T-Drive units shipped in the Nov 2024 batch. An OTA patch (v3.4.2) is being pushed to all affected units now — expected restore time is 15–20 minutes. As a fallback, drivers on AU-112, AU-119, and AU-127 have been notified via in-cab alert to manually check in every 30 minutes until tracking is restored. We'll send a full incident report once resolved.",
      aiPriority: Priority.HIGH,
      aiAnalyzedAt: new Date(Date.now() - 1000 * 60 * 45),
      customerId: jordan.id,
      assignedAgentId: auraAgent.id,
    },
    {
      subject: "Customs clearance failed — documentation error on HS code",
      description: "Shipment AWB-229148 was rejected at Lagos Port customs due to an incorrect HS code (declared as 8471.30 instead of 8471.41 for laptops). We are losing $4,000/day in demurrage. This needs to be corrected and resubmitted today.",
      status: TicketStatus.IN_PROGRESS,
      priority: Priority.CRITICAL,
      channel: Channel.PHONE,
      tags: ["customs", "hs-code", "demurrage", "urgent"],
      aiSuggestedResponse: "Dear Amara, I've confirmed the HS code discrepancy on AWB-229148. Our customs broker in Lagos (Global Clearance Ltd, contact: +234-80-555-0199) is preparing the amended entry now. The corrected HS code 8471.41 is already verified with Nigerian Customs Service. We expect resubmission within 3 hours. Regarding demurrage: Aura Logistics accepts responsibility for the documentation error — we will cover demurrage costs from the rejection date. Please send your demurrage invoice to billing@aura-logistics.com.",
      aiPriority: Priority.CRITICAL,
      aiAnalyzedAt: new Date(Date.now() - 1000 * 60 * 20),
      customerId: amara.id,
      assignedAgentId: auraAgent.id,
    },
    {
      subject: "Warehouse temperature log missing for February shipment",
      description: "Our compliance team requires the cold-chain temperature log for Shipment SHP-0022 (Feb 14–18) stored at your Hamburg facility. The log was not included in the delivery documentation. We need this for our pharmaceutical audit.",
      status: TicketStatus.RESOLVED,
      priority: Priority.MEDIUM,
      channel: Channel.EMAIL,
      tags: ["compliance", "cold-chain", "documentation"],
      aiSuggestedResponse: "Hello Lena, I've retrieved the temperature log for SHP-0022 from our Hamburg cold-storage system. The log shows continuous compliance at 2–8°C throughout the storage period (Feb 14–18). The PDF report and the raw IoT sensor export are attached. For your pharmaceutical audit, I've also included the facility's ISO 13485 certification (valid until Dec 2026). Please let me know if you need any additional compliance documentation.",
      aiPriority: Priority.MEDIUM,
      aiAnalyzedAt: new Date(Date.now() - 1000 * 60 * 60 * 48),
      customerId: lena.id,
      assignedAgentId: auraAgent.id,
      resolvedAt: new Date(Date.now() - 1000 * 60 * 60 * 24),
    },
    {
      subject: "Change delivery address after dispatch — Order #AL-5001",
      description: "I need to redirect Order #AL-5001 from our Warehouse A to Warehouse B (new address: 44 Harbourview Rd, Sydney 2000). The driver was already dispatched 2 hours ago. Is this still possible?",
      status: TicketStatus.WAITING_ON_CUSTOMER,
      priority: Priority.HIGH,
      channel: Channel.CHAT,
      tags: ["reroute", "delivery"],
      aiSuggestedResponse: "Hi Marcus, I've contacted the driver and reroute is possible — but we need written authorisation from your account manager (per your SLA agreement, Clause 4.2) before we can redirect a live shipment. I've sent a DocuSign request to the email on file. Once signed, the reroute will be confirmed within 15 minutes. Please note a $45 reroute fee applies per your rate card.",
      aiPriority: Priority.HIGH,
      aiAnalyzedAt: new Date(Date.now() - 1000 * 60 * 60 * 3),
      customerId: marcus.id,
      assignedAgentId: auraAgent.id,
    },
    {
      subject: "Emergency cold chain failure — Shipment SHP-0089",
      description: "Temperature sensor on SHP-0089 (insulin shipment) just triggered a breach alert — temp reading 12°C for the past 40 minutes. Container is currently in transit. This is a patient safety issue.",
      status: TicketStatus.OPEN,
      priority: Priority.CRITICAL,
      channel: Channel.API,
      tags: ["cold-chain", "breach", "patient-safety", "insulin"],
      aiSuggestedResponse: "URGENT ESCALATION — SHP-0089 Cold Chain Breach\n\nPriya, I've immediately notified our crisis response team and the driver (ETA to nearest cold-storage depot: 22 minutes). The Sensitech monitor log has been exported and sent to our QA team. Preliminary assessment: the breach is isolated to the secondary insulation layer — primary pharmaceutical zone is reading 6.2°C and within spec. Our QA manager will call you within 10 minutes to determine shipment disposition. Please have your pharmacovigilance contact available.",
      aiPriority: Priority.CRITICAL,
      aiAnalyzedAt: new Date(Date.now() - 1000 * 60 * 5),
      customerId: priya.id,
      assignedAgentId: auraAgent.id,
    },
    {
      subject: "API webhook for shipment tracking not firing",
      description: "Our integration depends on the webhook at POST /v2/shipments/events. As of yesterday it stopped sending events for status transitions. We've verified our endpoint is healthy — the events simply aren't being dispatched from your side.",
      status: TicketStatus.IN_PROGRESS,
      priority: Priority.MEDIUM,
      channel: Channel.API,
      tags: ["api", "webhook", "integration"],
      aiSuggestedResponse: "Hi Jordan, our engineering team has identified the issue: a deployment last night introduced a bug in the event dispatcher that caused webhook retries to silently fail after the first attempt. A hotfix (v2.14.3) was deployed 30 minutes ago. Webhooks should now be firing correctly. Please confirm receipt of the backlog of missed events — we'll replay the last 24 hours of events to your endpoint on request.",
      aiPriority: Priority.MEDIUM,
      aiAnalyzedAt: new Date(Date.now() - 1000 * 60 * 60 * 5),
      customerId: jordan.id,
      assignedAgentId: auraAgent.id,
    },
    {
      subject: "Delivery confirmation email not received for #AL-4777",
      description: "We've been waiting 3 days for a delivery confirmation on Order #AL-4777. The tracking portal shows 'Delivered' but we haven't received the POD (Proof of Delivery) or email confirmation.",
      status: TicketStatus.OPEN,
      priority: Priority.MEDIUM,
      channel: Channel.EMAIL,
      tags: ["pod", "delivery-confirmation"],
      aiSuggestedResponse: "Dear Amara, I've located the signed POD for Order #AL-4777. It was signed by 'K. Mensah' on March 18 at 14:22 local time. I'm resending it to your registered email now. It appears the original email landed in spam — our system shows it was delivered but not opened. The POD document is also available in your client portal under Orders > #AL-4777 > Documents.",
      aiPriority: Priority.LOW,
      aiAnalyzedAt: new Date(Date.now() - 1000 * 60 * 60 * 24),
      customerId: amara.id,
      assignedAgentId: auraAgent.id,
    },
    {
      subject: "Fleet vehicle AU-089 breakdown — urgent reroute",
      description: "Vehicle AU-089 broke down on the A1 motorway near Stuttgart. It's carrying time-sensitive automotive parts due at the BMW plant in Munich by 06:00 tomorrow. We need an emergency transfer to a replacement vehicle ASAP.",
      status: TicketStatus.OPEN,
      priority: Priority.CRITICAL,
      channel: Channel.PHONE,
      tags: ["breakdown", "reroute", "automotive", "urgent"],
      aiSuggestedResponse: "Lena, I've dispatched emergency vehicle AU-142 (currently 34km from the breakdown location, ETA 28 minutes) to complete the transfer. The BMW Munich receiving dock has been notified — they've extended the delivery window to 07:30 to accommodate. Recovery crew is also en route to AU-089. Please ask the driver to stay with the vehicle and await the transfer crew. I'll send a live tracking link for AU-142 via SMS to the driver's registered number now.",
      aiPriority: Priority.CRITICAL,
      aiAnalyzedAt: new Date(Date.now() - 1000 * 60 * 15),
      customerId: lena.id,
      assignedAgentId: auraAgent.id,
    },
    {
      subject: "Monthly summary report missing last 3 entries",
      description: "The March summary report downloaded from our portal is missing the last 3 shipments (March 26–28). Everything before that date is present. Can you resend or fix the report?",
      status: TicketStatus.RESOLVED,
      priority: Priority.LOW,
      channel: Channel.EMAIL,
      tags: ["reporting", "portal"],
      aiSuggestedResponse: "Hi Marcus, this was a known pagination bug in the report generator that cut off entries beyond page 10 when a month had more than 50 shipments. The fix was deployed this morning. Your March report has been regenerated and is now available in the portal — all 53 shipments are included. I've also emailed you the updated PDF directly. We apologise for the inconvenience.",
      aiPriority: Priority.LOW,
      aiAnalyzedAt: new Date(Date.now() - 1000 * 60 * 60 * 72),
      customerId: marcus.id,
      assignedAgentId: auraAgent.id,
      resolvedAt: new Date(Date.now() - 1000 * 60 * 60 * 48),
    },
    {
      subject: "Damaged goods claim #DG-2291 — 14 pallets",
      description: "Delivery of 14 pallets of electronics (Order #AL-4901) arrived with visible forklift damage to 6 pallets. We have photos and an independent surveyor's report. Total estimated damage: $28,500. Please initiate the insurance claim process.",
      status: TicketStatus.IN_PROGRESS,
      priority: Priority.HIGH,
      channel: Channel.EMAIL,
      tags: ["claims", "damage", "insurance"],
      aiSuggestedResponse: "Dear Jordan, I've opened claim #DG-2291 in our cargo claims system and notified our insurer (Zurich Cargo, Policy ZC-8841). Please upload your photos and surveyor report to the claims portal at claims.aura-logistics.com/DG-2291. We'll also request the driver's incident report and warehouse loading CCTV footage. Standard processing is 10–14 business days; given the claim value we're escalating to our senior claims adjuster for priority review.",
      aiPriority: Priority.HIGH,
      aiAnalyzedAt: new Date(Date.now() - 1000 * 60 * 60 * 36),
      customerId: jordan.id,
      assignedAgentId: auraAgent.id,
    },
    {
      subject: "Last-mile delivery failure in rural zone — Order #AL-5103",
      description: "Order #AL-5103 was marked 'undeliverable' due to an access road restriction, but no one contacted us to arrange an alternative. The customer at the delivery point is waiting. This has happened 3 times this month with rural addresses.",
      status: TicketStatus.OPEN,
      priority: Priority.HIGH,
      channel: Channel.EMAIL,
      tags: ["last-mile", "rural", "pattern-issue"],
      aiSuggestedResponse: "Hi Amara, I've reviewed the last-mile routing for your rural deliveries and identified a configuration issue — your account's rural exception protocol was not set to 'Contact Before Return.' I've updated this setting now, so all future rural deliveries will trigger a call to the consignee before any 'undeliverable' action is taken.\n\nFor Order #AL-5103, I've re-dispatched to a local courier partner (Swift Rural Logistics) who has off-road capability — new ETA is tomorrow morning. I'm also raising a service review for the 3 failed deliveries this month to ensure full accountability.",
      aiPriority: Priority.HIGH,
      aiAnalyzedAt: new Date(Date.now() - 1000 * 60 * 60 * 8),
      customerId: amara.id,
      assignedAgentId: auraAgent.id,
    },
    {
      subject: "HAZMAT compliance question — Class 3 flammable liquids",
      description: "We need to ship Class 3 flammable liquids (paint thinner, 200L) from Frankfurt to Istanbul. What documentation, packaging, and labelling does Aura Logistics require to accept this shipment? First time shipping HAZMAT with you.",
      status: TicketStatus.OPEN,
      priority: Priority.MEDIUM,
      channel: Channel.EMAIL,
      tags: ["hazmat", "compliance", "class-3"],
      aiSuggestedResponse: "Hello Marcus, great that you're planning ahead on HAZMAT compliance. For Class 3 flammable liquids via road (Frankfurt → Istanbul, crossing through Austria and Bulgaria), you'll need:\n\n1. UN number and proper shipping name on all outer packaging (UN1263 – Paint, Flammable Liquid)\n2. ADR-compliant UN-approved packaging (Packing Group II or III depending on flash point)\n3. MSDS / SDS for each product\n4. Transport Emergency Card (TREMCARD)\n5. Driver ADR certificate + vehicle ADR equipment checklist\n\nOur HAZMAT team will review your documentation before acceptance. Please email hazmat@aura-logistics.com with your SDS sheets to start the pre-approval process.",
      aiPriority: Priority.MEDIUM,
      aiAnalyzedAt: new Date(Date.now() - 1000 * 60 * 60 * 12),
      customerId: marcus.id,
      assignedAgentId: auraAgent.id,
    },
    {
      subject: "Bulk rate negotiation for Q2 2025",
      description: "We're planning a significant volume increase in Q2 (estimating 40+ shipments/month). Looking to renegotiate our rate card to reflect the increased commitment. Can we schedule a call with your commercial team?",
      status: TicketStatus.CLOSED,
      priority: Priority.LOW,
      channel: Channel.EMAIL,
      tags: ["commercial", "rate-negotiation"],
      aiSuggestedResponse: "Hi Priya, congratulations on the volume growth — we'd love to discuss a revised rate structure that reflects your Q2 commitment. I've connected you with our commercial director, Sarah Okonkwo (sarah.okonkwo@aura-logistics.com), who handles key account negotiations. She'll reach out within 24 hours to schedule a call. In the meantime, I can share our preliminary volume-discount tiers for your reference.",
      aiPriority: Priority.LOW,
      aiAnalyzedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5),
      customerId: priya.id,
      assignedAgentId: auraAgent.id,
      resolvedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4),
    },
    {
      subject: "Payment portal error — unable to complete invoice payment",
      description: "Getting an error on the payment portal: 'Transaction failed: Payment method not supported.' We're trying to pay Invoice #INV-3301 ($8,200) via bank transfer from our EU account. The portal seems to reject non-UK account numbers.",
      status: TicketStatus.RESOLVED,
      priority: Priority.MEDIUM,
      channel: Channel.CHAT,
      tags: ["billing", "payment-portal", "bug"],
      aiSuggestedResponse: "Hello Lena, the payment portal currently only supports UK and US bank accounts for direct payment — a known limitation we're working to resolve. For EU accounts, please use our SEPA transfer details:\n\nBank: Deutsche Bank Frankfurt\nIBAN: DE89 3704 0044 0532 0130 00\nBIC: COBADEFFXXX\nReference: INV-3301\n\nAlternatively, I can send you a Stripe payment link that accepts EU cards. The portal update to support SEPA direct is scheduled for Q2.",
      aiPriority: Priority.MEDIUM,
      aiAnalyzedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3),
      customerId: lena.id,
      assignedAgentId: auraAgent.id,
      resolvedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2),
    },
    {
      subject: "New onboarding — API integration setup help",
      description: "Just signed up and trying to set up the API integration for our warehouse management system. The docs mention an API key and a webhook URL but I'm not finding where to generate these in the dashboard.",
      status: TicketStatus.CLOSED,
      priority: Priority.LOW,
      channel: Channel.CHAT,
      tags: ["onboarding", "api", "integration"],
      aiSuggestedResponse: "Welcome, Jordan! To get your API credentials: go to Dashboard > Settings > API Keys and click 'Generate New Key.' Name it something descriptive like 'WMS Integration.' For webhooks, go to Settings > Webhooks and add your endpoint URL — you can subscribe to specific event types (shipment.created, status.updated, etc.). Our API docs are at docs.aura-logistics.com — the Quickstart guide should have you running in under 30 minutes. Happy to jump on a quick call if you get stuck.",
      aiPriority: Priority.LOW,
      aiAnalyzedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7),
      customerId: jordan.id,
      assignedAgentId: auraAgent.id,
      resolvedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 6),
    },
  ]

  for (const t of auraTickets) {
    await prisma.ticket.create({ data: { ...t, tenantId: aura.id } })
  }

  // ── TENANT 2: Pixel Stream ───────────────────────────────────
  console.log("   Creating Pixel Stream...")
  const pixel = await prisma.tenant.create({
    data: { name: "Pixel Stream", slug: "pixel-stream", plan: Plan.STARTER },
  })

  const pixelAgent = await prisma.user.create({
    data: {
      clerkId: "seed_pixelstream_agent_001",
      email: "support@pixelstream.io",
      name: "Casey Morgan",
      role: Role.OWNER,
      tenantId: pixel.id,
    },
  })

  const [tyler, keiko, diego, fatima] = await Promise.all([
    prisma.customer.create({ data: { tenantId: pixel.id, email: "tyler@streamvault.io", name: "Tyler Ross" } }),
    prisma.customer.create({ data: { tenantId: pixel.id, email: "keiko@tokyomedia.jp", name: "Keiko Tanaka" } }),
    prisma.customer.create({ data: { tenantId: pixel.id, email: "diego@latinflux.mx", name: "Diego Alvarez" } }),
    prisma.customer.create({ data: { tenantId: pixel.id, email: "fatima@gulfstream.ae", name: "Fatima Al-Harbi" } }),
  ])

  const pixelTickets = [
    {
      subject: "4K stream stuttering during peak hours (18:00–22:00 UTC)",
      description: "Our 4K live streams are experiencing heavy buffering every evening between 18:00–22:00 UTC. SD streams are fine. The issue started 4 days ago and is impacting ~40% of our premium subscribers.",
      status: TicketStatus.OPEN,
      priority: Priority.HIGH,
      channel: Channel.EMAIL,
      tags: ["streaming", "performance", "4k", "peak-traffic"],
      aiSuggestedResponse: "Hi Tyler, the 4K stuttering during peak hours is consistent with a CDN edge capacity issue on the US-East-2 PoP, which handles ~60% of your subscriber base. Our CDN team is increasing edge capacity — expect full resolution within 4 hours. As an immediate mitigation, I've enabled adaptive bitrate capping (max 1080p60) for peak hours only — this will prevent buffering while maintaining excellent quality. We'll notify you before restoring full 4K capacity. Credits for affected premium subscribers will be automatically applied.",
      aiPriority: Priority.HIGH,
      aiAnalyzedAt: new Date(Date.now() - 1000 * 60 * 60 * 2),
      customerId: tyler.id,
      assignedAgentId: pixelAgent.id,
    },
    {
      subject: "Video encoding fails on uploads larger than 2GB",
      description: "Any video uploaded over 2GB fails at the encoding stage with error: 'Job timeout after 3600s.' We're producing 4K documentary content averaging 4–8GB per file. This is blocking our entire upload workflow.",
      status: TicketStatus.IN_PROGRESS,
      priority: Priority.HIGH,
      channel: Channel.EMAIL,
      tags: ["encoding", "upload", "timeout", "4k"],
      aiSuggestedResponse: "Hello Keiko, the 3600s encoding timeout was a hard limit set for our Starter tier. Given your 4K documentary workflow, this is clearly insufficient. I've temporarily raised your encoding timeout to 7200s (2 hours) and upgraded your processing queue to our high-memory encoder cluster, which handles large files significantly faster.\n\nFor files over 4GB, I also recommend using our chunked upload API (docs.pixelstream.io/upload/chunked) which is more resilient than the browser uploader. Could you retry your largest file now and let me know the result?",
      aiPriority: Priority.HIGH,
      aiAnalyzedAt: new Date(Date.now() - 1000 * 60 * 60 * 5),
      customerId: keiko.id,
      assignedAgentId: pixelAgent.id,
    },
    {
      subject: "CDN edge node returning 503 in Mexico City region",
      description: "We're getting consistent 503 errors from the CDN for users in Mexico City and surrounding area (MX-09). About 2,000 affected viewers right now. This is our biggest market. The issue has been ongoing for 2.5 hours.",
      status: TicketStatus.OPEN,
      priority: Priority.CRITICAL,
      channel: Channel.CHAT,
      tags: ["cdn", "503", "mexico", "outage"],
      aiSuggestedResponse: "Diego, I've confirmed a hardware failure at our Mexico City PoP (GDL-MEX-03). Traffic is being rerouted to our Dallas fallback node — you may see a latency increase of 40–60ms for Mexico City users, but streams should resume within 5 minutes. Our infrastructure team has a replacement blade being swapped now — expected full restoration at the primary PoP: 90 minutes. Status page updated at status.pixelstream.io. I'll DM you when the primary PoP is back online.",
      aiPriority: Priority.CRITICAL,
      aiAnalyzedAt: new Date(Date.now() - 1000 * 60 * 10),
      customerId: diego.id,
      assignedAgentId: pixelAgent.id,
    },
    {
      subject: "Subtitle sync off by 3.2 seconds on all Arabic content",
      description: "Arabic subtitles on all our Gulf region content are consistently 3.2 seconds behind the audio. This started after the platform update last week. English and French subtitles are fine.",
      status: TicketStatus.RESOLVED,
      priority: Priority.MEDIUM,
      channel: Channel.EMAIL,
      tags: ["subtitles", "localisation", "arabic", "regression"],
      aiSuggestedResponse: "Hello Fatima, we identified the root cause: the v2.8.1 platform update introduced a timing offset bug specifically for RTL subtitle tracks when the source video has a non-zero start timecode. A patch (v2.8.2) was deployed 2 hours ago — all Arabic subtitle tracks have been reprocessed. Please clear your CDN cache and verify with a test stream. We've also added an automated sync accuracy test to our regression suite to prevent recurrence.",
      aiPriority: Priority.MEDIUM,
      aiAnalyzedAt: new Date(Date.now() - 1000 * 60 * 60 * 48),
      customerId: fatima.id,
      assignedAgentId: pixelAgent.id,
      resolvedAt: new Date(Date.now() - 1000 * 60 * 60 * 24),
    },
    {
      subject: "Ad insertion breaking live stream — viewers see black screen",
      description: "When our pre-roll ads are inserted during the live stream, viewers see a 4–8 second black screen instead of a smooth transition. This is causing significant drop-off. SSAI configuration hasn't changed on our end.",
      status: TicketStatus.IN_PROGRESS,
      priority: Priority.HIGH,
      channel: Channel.EMAIL,
      tags: ["ads", "ssai", "live-stream", "regression"],
      aiSuggestedResponse: "Tyler, after reviewing your SSAI manifest logs, we found that our ad stitching service is sending an MPEG-TS discontinuity marker that isn't being handled correctly by the player SDK (v4.2.1 has a known regression for this). Two options: (1) Roll back the player SDK to v4.1.9 — I can do this for your account immediately; or (2) Enable our 'smooth splice' beta feature which pre-buffers the ad before insertion. Most broadcasters are choosing option 2. Which would you prefer?",
      aiPriority: Priority.HIGH,
      aiAnalyzedAt: new Date(Date.now() - 1000 * 60 * 60 * 6),
      customerId: tyler.id,
      assignedAgentId: pixelAgent.id,
    },
    {
      subject: "Analytics dashboard showing zero views for last 48 hours",
      description: "Our analytics dashboard shows 0 views for the past 48 hours across all content. We can confirm from our own logs that streams are being watched. This makes it impossible to report to our advertisers.",
      status: TicketStatus.OPEN,
      priority: Priority.MEDIUM,
      channel: Channel.EMAIL,
      tags: ["analytics", "dashboard", "reporting"],
      aiSuggestedResponse: "Hello Keiko, the analytics pipeline had a data processing outage from March 20 18:00 UTC to March 22 06:00 UTC, which is why the dashboard shows zeros. The underlying view data was captured and stored correctly — it just wasn't aggregated. Our data team is running the backfill job now (estimated completion: 3–4 hours). Your advertiser reports will reflect accurate numbers once complete. For urgent advertiser needs, I can export the raw event data as a CSV right now.",
      aiPriority: Priority.MEDIUM,
      aiAnalyzedAt: new Date(Date.now() - 1000 * 60 * 60 * 4),
      customerId: keiko.id,
      assignedAgentId: pixelAgent.id,
    },
    {
      subject: "DRM license renewal failing — content unplayable for subscribers",
      description: "Subscribers are getting 'License expired' errors on all premium content. This started about 90 minutes ago. The DRM license server appears to be rejecting renewals. This is our entire premium catalog.",
      status: TicketStatus.IN_PROGRESS,
      priority: Priority.CRITICAL,
      channel: Channel.API,
      tags: ["drm", "licensing", "outage", "premium"],
      aiSuggestedResponse: "Tyler — CRITICAL INCIDENT OPENED (INC-4491).\n\nWe've identified the issue: our DRM license server SSL certificate auto-renewed successfully but the CDN hasn't propagated the new cert yet, causing validation failures. ETA to fix: 20 minutes. As an immediate workaround, I've temporarily extended all active license tokens by 4 hours server-side — subscribers who re-open the app will get unblocked immediately.\n\nIncident updates at status.pixelstream.io every 10 minutes. I'll call you directly once the CDN propagation is complete.",
      aiPriority: Priority.CRITICAL,
      aiAnalyzedAt: new Date(Date.now() - 1000 * 60 * 25),
      customerId: tyler.id,
      assignedAgentId: pixelAgent.id,
    },
    {
      subject: "Embedded player not loading on iOS Safari 17",
      description: "Our embedded player fails to load on iOS Safari 17 (iPhone 15 / iPad). The player div is blank — no error, no spinner. Works fine on Chrome iOS and desktop browsers. Affecting all our mobile embed placements.",
      status: TicketStatus.OPEN,
      priority: Priority.HIGH,
      channel: Channel.EMAIL,
      tags: ["player", "ios", "safari", "mobile"],
      aiSuggestedResponse: "Hi Fatima, this is a known compatibility issue with iOS Safari 17's new CSP enforcement for iframes with 'allow-scripts'. The fix is to add 'allow-same-origin allow-scripts' to your embed iframe's sandbox attribute. Here's the corrected embed code:\n\n```html\n<iframe src=\"https://player.pixelstream.io/embed/[ID]\" sandbox=\"allow-scripts allow-same-origin allow-presentation\" ...>\n```\n\nOur documentation has been updated. We're also shipping a player update next week that handles this automatically without requiring the sandbox attribute change.",
      aiPriority: Priority.HIGH,
      aiAnalyzedAt: new Date(Date.now() - 1000 * 60 * 60 * 12),
      customerId: fatima.id,
      assignedAgentId: pixelAgent.id,
    },
    {
      subject: "API rate limit too low — hitting 429 during upload batches",
      description: "We're getting 429 rate limit errors when uploading batch content (typically 50–100 videos at once). Our current limit appears to be 10 req/sec. Competitor platforms offer 100 req/sec minimum. Please increase.",
      status: TicketStatus.RESOLVED,
      priority: Priority.MEDIUM,
      channel: Channel.EMAIL,
      tags: ["api", "rate-limit", "batch-upload"],
      aiSuggestedResponse: "Hi Diego, I've increased your API rate limit from 10 req/s to 50 req/s effective immediately — this should handle your batch upload workflow comfortably. For even larger batches (100+ simultaneous uploads), I recommend using our Batch Upload API endpoint (/v2/uploads/batch) which is exempt from per-request rate limits and uses a job queue model. Detailed docs are at docs.pixelstream.io/batch-upload.",
      aiPriority: Priority.LOW,
      aiAnalyzedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3),
      customerId: diego.id,
      assignedAgentId: pixelAgent.id,
      resolvedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2),
    },
    {
      subject: "Content geo-restriction not applying to Japan region",
      description: "We've configured our content to be restricted from JP (Japan) in the rights management settings, but Japanese IP addresses can still stream it. This is a rights violation and needs immediate fixing.",
      status: TicketStatus.OPEN,
      priority: Priority.HIGH,
      channel: Channel.EMAIL,
      tags: ["geo-restriction", "rights-management", "japan", "compliance"],
      aiSuggestedResponse: "Keiko, this is serious — I've escalated to our rights management engineering team immediately. Preliminary investigation shows the JP geo-block was set at the account level but not propagated to 3 of our 8 CDN PoPs in the APAC region. As an immediate measure, I've applied the restriction at the edge level on all APAC PoPs (takes effect in 5 minutes). Our team will do a full audit of all your geo-restriction rules across all PoPs within the hour and provide a written incident report for your rights holders.",
      aiPriority: Priority.HIGH,
      aiAnalyzedAt: new Date(Date.now() - 1000 * 60 * 60 * 2),
      customerId: keiko.id,
      assignedAgentId: pixelAgent.id,
    },
    {
      subject: "Thumbnail generation queue stuck — 200+ videos pending",
      description: "Thumbnail generation hasn't processed for 6 hours. We have 200+ videos in the queue all showing 'Processing...' and none completing. Thumbnails are required before we can publish content.",
      status: TicketStatus.RESOLVED,
      priority: Priority.LOW,
      channel: Channel.EMAIL,
      tags: ["thumbnails", "queue", "processing"],
      aiSuggestedResponse: "Hi Keiko, the thumbnail generation queue was stuck due to a deadlock in the processing worker introduced in our maintenance window this morning. The worker has been restarted and all 200+ pending videos are now processing — estimated completion: 45 minutes. Going forward, we've implemented a watchdog service that automatically detects and restarts stalled queues within 5 minutes. I'll let you know when all your thumbnails are ready.",
      aiPriority: Priority.LOW,
      aiAnalyzedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2),
      customerId: keiko.id,
      assignedAgentId: pixelAgent.id,
      resolvedAt: new Date(Date.now() - 1000 * 60 * 60 * 20),
    },
    {
      subject: "Multi-language audio track missing from VOD after transcode",
      description: "Our Spanish-language audio track is missing from the final VOD output even though it was included in the source file. The English track is present. Issue affects all new uploads from this week.",
      status: TicketStatus.OPEN,
      priority: Priority.MEDIUM,
      channel: Channel.EMAIL,
      tags: ["audio", "transcode", "multi-language", "vod"],
      aiSuggestedResponse: "Hi Diego, we've reproduced the issue. A transcoding configuration change this week broke multi-track audio handling for non-English tracks when the source file uses Dolby E encoding. A fix is being tested and will be deployed within 6 hours. In the meantime, as a workaround: upload the Spanish audio as a separate .aac file and use our Audio Track API to attach it to the video. I can walk you through this process — reply or call our tech support line.",
      aiPriority: Priority.MEDIUM,
      aiAnalyzedAt: new Date(Date.now() - 1000 * 60 * 60 * 8),
      customerId: diego.id,
      assignedAgentId: pixelAgent.id,
    },
    {
      subject: "On-demand VOD transcoding taking 8x longer than usual",
      description: "Our VOD uploads that normally take 10–15 minutes to transcode are now taking 90+ minutes. This is blocking our content schedule. No changes on our end.",
      status: TicketStatus.RESOLVED,
      priority: Priority.MEDIUM,
      channel: Channel.EMAIL,
      tags: ["transcode", "vod", "performance"],
      aiSuggestedResponse: "Hello Diego, a shared transcoding node group experienced degraded hardware performance starting yesterday — it continued to accept jobs but at 1/8th normal speed. The affected nodes have been taken offline and replaced. Your queue should now be processing at normal speed. The 3 videos currently in queue will complete within the next 20 minutes. We've also increased our transcoding fleet capacity by 30% to handle peak loads. Apologies for the disruption to your content schedule.",
      aiPriority: Priority.MEDIUM,
      aiAnalyzedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 1),
      customerId: diego.id,
      assignedAgentId: pixelAgent.id,
      resolvedAt: new Date(Date.now() - 1000 * 60 * 60 * 18),
    },
    {
      subject: "Bandwidth usage spike not showing in billing dashboard",
      description: "We ran a major live event last weekend with 80,000 concurrent viewers but our billing dashboard still shows our normal monthly usage. We want to confirm the overage charges before our invoice arrives.",
      status: TicketStatus.CLOSED,
      priority: Priority.LOW,
      channel: Channel.EMAIL,
      tags: ["billing", "bandwidth", "event"],
      aiSuggestedResponse: "Hi Fatima, the billing dashboard has a 48-hour delay for large events to allow for CDN log aggregation. Your event data is being processed now. Preliminary estimate: 42TB of bandwidth, which puts you in the 40–50TB tier at your contracted rate of $0.012/GB. Estimated overage: $504. You'll see the final figure on your dashboard within 24 hours. Your next invoice will include the overage as a separate line item. Let me know if you'd like a detailed breakdown by PoP.",
      aiPriority: Priority.LOW,
      aiAnalyzedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4),
      customerId: fatima.id,
      assignedAgentId: pixelAgent.id,
      resolvedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3),
    },
    {
      subject: "Stream key rotation — security precaution after team change",
      description: "We recently had a team member leave and need to rotate all our RTMP stream keys as a security precaution. How do we do this for all 12 of our channels at once?",
      status: TicketStatus.CLOSED,
      priority: Priority.LOW,
      channel: Channel.CHAT,
      tags: ["security", "stream-keys", "offboarding"],
      aiSuggestedResponse: "Hi Tyler, you can rotate all stream keys at once via API: call POST /v2/channels/rotate-keys with your account token, or from the dashboard under Settings > Stream Keys > Rotate All. All existing keys are immediately invalidated. Note: any active streams using old keys will be disconnected — plan the rotation for a low-traffic window. We also recommend enabling IP allowlisting for stream keys (Settings > Security) to prevent future exposure. Let me know if you need help with the API approach.",
      aiPriority: Priority.LOW,
      aiAnalyzedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5),
      customerId: tyler.id,
      assignedAgentId: pixelAgent.id,
      resolvedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4),
    },
  ]

  for (const t of pixelTickets) {
    await prisma.ticket.create({ data: { ...t, tenantId: pixel.id } })
  }

  // ── TENANT 3: GreenLeaf Retail ───────────────────────────────
  console.log("   Creating GreenLeaf Retail...")
  const greenleaf = await prisma.tenant.create({
    data: { name: "GreenLeaf Retail", slug: "greenleaf-retail", plan: Plan.ENTERPRISE },
  })

  const greenAgent = await prisma.user.create({
    data: {
      clerkId: "seed_greenleaf_agent_001",
      email: "support@greenleaf-retail.com",
      name: "Sam Patel",
      role: Role.OWNER,
      tenantId: greenleaf.id,
    },
  })

  const [sophie, james, mei, rafael, ingrid] = await Promise.all([
    prisma.customer.create({ data: { tenantId: greenleaf.id, email: "sophie@naturalnest.co.uk", name: "Sophie Turner" } }),
    prisma.customer.create({ data: { tenantId: greenleaf.id, email: "james@organicfarm.ng", name: "James Okafor" } }),
    prisma.customer.create({ data: { tenantId: greenleaf.id, email: "mei@ecobasket.sg", name: "Mei Lin" } }),
    prisma.customer.create({ data: { tenantId: greenleaf.id, email: "rafael@verdebrasil.com.br", name: "Rafael Costa" } }),
    prisma.customer.create({ data: { tenantId: greenleaf.id, email: "ingrid@nordic-eco.no", name: "Ingrid Sorensen" } }),
  ])

  const greenTickets = [
    {
      subject: "Order #GL-3821 not delivered — 8 days overdue",
      description: "Order #GL-3821 was placed on March 12 with a 5-day delivery window, but it still hasn't arrived. Tracking shows it's been 'In Transit' at East Midlands depot for 6 days. The customer needs this for a corporate gifting event on March 25.",
      status: TicketStatus.OPEN,
      priority: Priority.HIGH,
      channel: Channel.EMAIL,
      tags: ["delivery", "overdue", "tracked"],
      aiSuggestedResponse: "Hello Sophie, I've investigated Order #GL-3821 and found it was held at East Midlands for a failed address verification (postcode scan mismatch). I've manually released the hold and re-scanned with the correct postcode — the parcel is now booked for tomorrow's priority delivery run. Given the 8-day delay, I've applied a full shipping refund and a £15 store credit to your account. For the corporate gifting event: I can also arrange a direct courier if tomorrow doesn't work — just reply to confirm.",
      aiPriority: Priority.HIGH,
      aiAnalyzedAt: new Date(Date.now() - 1000 * 60 * 60 * 3),
      customerId: sophie.id,
      assignedAgentId: greenAgent.id,
    },
    {
      subject: "Wrong item in eco bundle box — received vanilla instead of peppermint",
      description: "Received an Eco Wellness Bundle (Order #GL-4102) but the lip balm included was vanilla-mint instead of the ordered peppermint-eucalyptus. The rest of the bundle is correct. Not a huge issue but the customer specifically requested peppermint for allergy reasons.",
      status: TicketStatus.IN_PROGRESS,
      priority: Priority.HIGH,
      channel: Channel.EMAIL,
      tags: ["wrong-item", "allergy", "fulfilment"],
      aiSuggestedResponse: "James, thank you for flagging this — the allergy context makes this a priority for us. I've arranged an express replacement of the peppermint-eucalyptus lip balm (dispatching today, no return required for the incorrect item). I've also flagged the bundle packing station for a QA audit as this is the third vanilla/peppermint mix-up this week. A £5 store credit has been added to your account as an apology. Please confirm the allergy is only to vanilla and not any other bundle ingredients so I can add a note to the order.",
      aiPriority: Priority.HIGH,
      aiAnalyzedAt: new Date(Date.now() - 1000 * 60 * 60 * 5),
      customerId: james.id,
      assignedAgentId: greenAgent.id,
    },
    {
      subject: "Product listed as In Stock but sold out at checkout",
      description: "Multiple customers are reporting they add the Bamboo Skincare Set to cart (shown as In Stock), proceed to checkout, and get an 'Out of Stock' error at payment. This is frustrating customers and losing sales. We've had at least 40 abandoned carts today.",
      status: TicketStatus.OPEN,
      priority: Priority.CRITICAL,
      channel: Channel.CHAT,
      tags: ["inventory", "checkout", "stock-sync", "revenue-impact"],
      aiSuggestedResponse: "Sam, this is a P1 inventory sync issue. The Bamboo Skincare Set (SKU: BM-SKIN-003) has a race condition between the warehouse inventory system and the storefront — a batch of 200 units was reserved for a B2B order but the reservation didn't update the public stock flag. I've temporarily set the product to 'Out of Stock' on the storefront to stop further frustrated customers, and I'm escalating to your Shopify integration team to fix the sync pipeline. ETA for fix: 2 hours. Recommend sending a proactive email to the 40 abandoned cart customers with a 10% discount code.",
      aiPriority: Priority.CRITICAL,
      aiAnalyzedAt: new Date(Date.now() - 1000 * 60 * 20),
      customerId: james.id,
      assignedAgentId: greenAgent.id,
    },
    {
      subject: "Subscription auto-renewal failed — account shows expired",
      description: "My GreenLeaf subscription auto-renewed last week but my bank confirmed the payment was taken. The account still shows 'Expired.' I've sent two emails already with no response. I need my benefits restored today.",
      status: TicketStatus.OPEN,
      priority: Priority.HIGH,
      channel: Channel.EMAIL,
      tags: ["subscription", "billing", "payment"],
      aiSuggestedResponse: "Sophie, I sincerely apologise for the delay and the frustration — two unanswered emails is unacceptable. I've traced the issue: your payment processed successfully (Ref: STR-8821-CH) but a Stripe webhook failure meant our system didn't receive the confirmation. I've manually updated your subscription to Active and extended it by one month as compensation for the inconvenience. Your member benefits are restored now. I'm also escalating the missed email responses to our support manager.",
      aiPriority: Priority.HIGH,
      aiAnalyzedAt: new Date(Date.now() - 1000 * 60 * 60 * 4),
      customerId: sophie.id,
      assignedAgentId: greenAgent.id,
    },
    {
      subject: "Loyalty points not credited after £180 purchase",
      description: "Made a £180 purchase last Tuesday and should have received 180 points (1pt per £1), but my loyalty balance hasn't updated. Screenshot of the order confirmation attached.",
      status: TicketStatus.RESOLVED,
      priority: Priority.LOW,
      channel: Channel.EMAIL,
      tags: ["loyalty", "points", "billing"],
      aiSuggestedResponse: "Hi Mei, I've reviewed your account and can see the 180 points from Order #GL-3988 were held in a 'pending' state because your account address didn't match the delivery address — a fraud prevention check we do for first-time large orders. I've approved the points manually and they're now available in your balance. Future orders on this address will process points automatically. Your current balance is 430 points — enough for a £4.30 discount on your next order.",
      aiPriority: Priority.LOW,
      aiAnalyzedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2),
      customerId: mei.id,
      assignedAgentId: greenAgent.id,
      resolvedAt: new Date(Date.now() - 1000 * 60 * 60 * 36),
    },
    {
      subject: "Carbon footprint report download not working",
      description: "The 'Download My Carbon Report' button on the account page just spins and never downloads anything. I need this report for a sustainability presentation to our board next week.",
      status: TicketStatus.IN_PROGRESS,
      priority: Priority.MEDIUM,
      channel: Channel.EMAIL,
      tags: ["sustainability", "reports", "download", "bug"],
      aiSuggestedResponse: "Hi Mei, the download issue is caused by a PDF generation timeout on accounts with more than 50 orders — the PDF builder is trying to include all historical orders and hitting a memory limit. Our team is deploying a fix that generates the report asynchronously and emails it to you. As an immediate fix: I've manually generated your carbon footprint report (covering all 2024–2025 orders) and attached it to this email. Your total carbon offset for the period: 47.3kg CO₂e, equivalent to planting 2.4 trees.",
      aiPriority: Priority.MEDIUM,
      aiAnalyzedAt: new Date(Date.now() - 1000 * 60 * 60 * 8),
      customerId: mei.id,
      assignedAgentId: greenAgent.id,
    },
    {
      subject: "Bulk B2B order inquiry — 500 eco gift boxes for conference",
      description: "We're hosting a sustainability conference in June (500 attendees) and want to order 500 eco gift boxes, ideally with custom branding. Looking for pricing, lead time, and minimum order quantity info.",
      status: TicketStatus.OPEN,
      priority: Priority.MEDIUM,
      channel: Channel.EMAIL,
      tags: ["b2b", "bulk-order", "custom-branding"],
      aiSuggestedResponse: "Hello Rafael, what a wonderful use case — thank you for thinking of GreenLeaf for your sustainability conference! For 500 eco gift boxes with custom branding:\n\n• Price (500 units): £18.50/box (includes custom box printing, 6% bulk discount)\n• Custom logo/messaging: £0.80/box additional for full-colour print\n• Lead time: 18–21 business days from artwork approval\n• Minimum order: 100 units\n\nI'm connecting you with our B2B partnerships team (b2b@greenleaf-retail.com) who can put together a formal proposal with branded mock-ups. Expect their response within 24 hours.",
      aiPriority: Priority.MEDIUM,
      aiAnalyzedAt: new Date(Date.now() - 1000 * 60 * 60 * 6),
      customerId: rafael.id,
      assignedAgentId: greenAgent.id,
    },
    {
      subject: "Return label not generated — Order #GL-3799",
      description: "Tried to initiate a return for Order #GL-3799 (biodegradable cleaning kit, wrong size). The return portal says 'Return Approved' but the label download gives a 500 error. I can't return without the label.",
      status: TicketStatus.IN_PROGRESS,
      priority: Priority.HIGH,
      channel: Channel.EMAIL,
      tags: ["returns", "label", "error", "portal"],
      aiSuggestedResponse: "Ingrid, I apologise for the portal error. Our Royal Mail returns API had a brief outage this morning that prevented label generation even for approved returns. I've manually generated your prepaid returns label (Royal Mail Tracked 48, valid for 28 days) and attached it to this email. Simply print and affix to the package. Once received, your refund for the cleaning kit will be processed within 3 business days. The portal bug has been fixed and new return requests should generate labels correctly.",
      aiPriority: Priority.HIGH,
      aiAnalyzedAt: new Date(Date.now() - 1000 * 60 * 60 * 3),
      customerId: ingrid.id,
      assignedAgentId: greenAgent.id,
    },
    {
      subject: "Product allergen info missing from Bee Pollen supplement listing",
      description: "The Bee Pollen supplement product page has no allergen warning despite containing a major allergen (bee pollen is an allergen for many people). This is a potential legal and safety issue. Several customers have flagged this to us.",
      status: TicketStatus.OPEN,
      priority: Priority.CRITICAL,
      channel: Channel.EMAIL,
      tags: ["allergen", "compliance", "product-safety", "legal"],
      aiSuggestedResponse: "Sam, this is a critical product safety issue — I've escalated it immediately to our content compliance team. The Bee Pollen supplement (SKU: SUPP-BP-001) has been temporarily unpublished from the storefront pending allergen information review and update. Our compliance team will add the required allergen declaration (\"Contains: Bee Pollen — may cause serious allergic reactions in sensitive individuals\") and EU Food Information Regulation compliant labelling within 2 hours, after which the product will be relisted. I recommend notifying recent purchasers as a precaution — I can pull the customer list for you.",
      aiPriority: Priority.CRITICAL,
      aiAnalyzedAt: new Date(Date.now() - 1000 * 60 * 30),
      customerId: mei.id,
      assignedAgentId: greenAgent.id,
    },
    {
      subject: "Packaging damaged on arrival — bamboo cutlery set",
      description: "Received the bamboo cutlery set (Order #GL-3621) but the packaging was visibly crushed. The actual cutlery appears fine but the presentation box is damaged — this was a gift. Disappointed with the packaging quality.",
      status: TicketStatus.RESOLVED,
      priority: Priority.MEDIUM,
      channel: Channel.EMAIL,
      tags: ["packaging", "damage", "gift"],
      aiSuggestedResponse: "Hello Ingrid, I'm truly sorry about the damaged gift packaging — first impressions matter, especially for gifts. I've arranged a replacement set in pristine condition, dispatched with upgraded gift packaging, to arrive within 2 days (no return required for the damaged set). I've also added a free personalised gift card service to your replacement order — just reply with a message to include. A £10 store credit has been added to your account for the inconvenience.",
      aiPriority: Priority.MEDIUM,
      aiAnalyzedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4),
      customerId: ingrid.id,
      assignedAgentId: greenAgent.id,
      resolvedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2),
    },
    {
      subject: "Discount code EARTH20 not applying at checkout",
      description: "The Earth Day discount code EARTH20 (20% off) isn't working at checkout. Getting the error: 'This coupon is not applicable to items in your cart.' I've tried 3 different carts with different products and the same error.",
      status: TicketStatus.RESOLVED,
      priority: Priority.MEDIUM,
      channel: Channel.CHAT,
      tags: ["discount", "checkout", "coupon"],
      aiSuggestedResponse: "Hi Sophie, the EARTH20 code was initially configured to exclude sale items and the 'Essentials' collection — which likely accounts for the error you're seeing. I've updated the code to apply to all products storewide (as it was intended). You can now use EARTH20 at checkout. The code is valid until April 25. If you had items in a cart that were affected, please add them again as the discount should now apply correctly.",
      aiPriority: Priority.LOW,
      aiAnalyzedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2),
      customerId: sophie.id,
      assignedAgentId: greenAgent.id,
      resolvedAt: new Date(Date.now() - 1000 * 60 * 60 * 36),
    },
    {
      subject: "Mobile app crashing on product barcode scan feature",
      description: "The 'Scan to Check Eco Score' feature in the GreenLeaf app crashes immediately on Android 14 devices. Works fine on iOS and older Android versions. This is our main selling feature and several customers have left 1-star reviews mentioning this.",
      status: TicketStatus.OPEN,
      priority: Priority.HIGH,
      channel: Channel.SOCIAL,
      tags: ["mobile", "android", "crash", "barcode"],
      aiSuggestedResponse: "James, thank you for escalating the Android 14 crash — I've reviewed the Play Store crash reports and confirmed the issue is in the camera permission handling for Android 14's new granular media permissions model. Our mobile team has identified the fix (updating to CameraX 1.4.0 which supports the new permission model) and is testing a patch build now. ETA for Play Store update: 48 hours.\n\nIn the meantime, users on Android 14 can access the Eco Score by manually entering the barcode number in the search bar. I've replied to the negative reviews with an apology and ETA for the fix.",
      aiPriority: Priority.HIGH,
      aiAnalyzedAt: new Date(Date.now() - 1000 * 60 * 60 * 5),
      customerId: james.id,
      assignedAgentId: greenAgent.id,
    },
    {
      subject: "Payment declined with valid card — unable to complete order",
      description: "My VISA card is being declined at checkout but I've confirmed with my bank the card is valid and has sufficient funds. My bank says GreenLeaf's payment processor is rejecting it, not the bank. Order value: £340.",
      status: TicketStatus.OPEN,
      priority: Priority.HIGH,
      channel: Channel.EMAIL,
      tags: ["payment", "checkout", "declined"],
      aiSuggestedResponse: "Hello Sophie, I've investigated the payment failure. Our fraud detection flagged your £340 order as it's the first order over £200 from your account with a delivery address different from your billing address. I've manually reviewed and whitelisted your account. Please retry checkout — the payment should go through now. I've also added a note to your account to prevent future false declines for deliveries to your workplace address. If it still fails, I can take the order over the phone or send a secure payment link.",
      aiPriority: Priority.HIGH,
      aiAnalyzedAt: new Date(Date.now() - 1000 * 60 * 60 * 2),
      customerId: sophie.id,
      assignedAgentId: greenAgent.id,
    },
    {
      subject: "Wholesale account approval — status inquiry",
      description: "Applied for a wholesale account 2 weeks ago and haven't heard back. We're a sustainable retailer in Brazil looking to stock GreenLeaf products. Our application ID is WHL-BR-0044.",
      status: TicketStatus.WAITING_ON_CUSTOMER,
      priority: Priority.MEDIUM,
      channel: Channel.EMAIL,
      tags: ["wholesale", "b2b", "onboarding"],
      aiSuggestedResponse: "Hello Rafael, I've located application WHL-BR-0044. Our wholesale team reviewed it and has a few follow-up questions before approval:\n\n1. Can you provide your CNPJ (Brazilian business registration number) for compliance?\n2. What is your estimated monthly order volume in £ GBP?\n3. Do you have an existing eco/sustainability certification (e.g., Rainforest Alliance, FSC, IFOAM)?\n\nOnce we have these details, approval is typically within 3 business days. Sincere apologies for the 2-week delay — this slipped through an internal handoff.",
      aiPriority: Priority.MEDIUM,
      aiAnalyzedAt: new Date(Date.now() - 1000 * 60 * 60 * 12),
      customerId: rafael.id,
      assignedAgentId: greenAgent.id,
    },
    {
      subject: "Newsletter unsubscribe not working — still receiving emails",
      description: "I've clicked 'Unsubscribe' in the footer of your newsletters at least 4 times over the past 2 weeks but keep receiving emails. This is a GDPR compliance issue.",
      status: TicketStatus.RESOLVED,
      priority: Priority.LOW,
      channel: Channel.EMAIL,
      tags: ["gdpr", "unsubscribe", "email", "compliance"],
      aiSuggestedResponse: "Hello Ingrid, I sincerely apologise for the repeated unsubscribe failures — you're right to flag this as a GDPR compliance concern. I've investigated and found that your email was in two separate mailing lists (general newsletter and eco tips series), and the unsubscribe link in the newsletter only removed you from one. I've removed your email from all GreenLeaf mailing lists immediately and added a global suppression flag. You will not receive any further marketing emails. I've also reported this dual-list unsubscribe bug to our CRM team for urgent fixing.",
      aiPriority: Priority.LOW,
      aiAnalyzedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3),
      customerId: ingrid.id,
      assignedAgentId: greenAgent.id,
      resolvedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2),
    },
    {
      subject: "Review submission returning 500 error",
      description: "Tried to leave a product review on the Reusable Beeswax Wraps page and got a 500 Internal Server Error after clicking Submit. Lost my full 3-paragraph review. Tried twice with the same result.",
      status: TicketStatus.RESOLVED,
      priority: Priority.MEDIUM,
      channel: Channel.EMAIL,
      tags: ["reviews", "500-error", "bug"],
      aiSuggestedResponse: "James, I'm sorry your review was lost twice — that's incredibly frustrating. The 500 error was caused by a profanity filter regex that was incorrectly flagging the word 'wrap' (as part of 'cling wrap') as disallowed content. A complete overhaul of the filter list was deployed 2 hours ago. Please try submitting your review again — it should work now. If you still have your review text, I'd love for you to resubmit. Otherwise, I can arrange a small credit as an apology for the lost effort.",
      aiPriority: Priority.MEDIUM,
      aiAnalyzedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 1),
      customerId: james.id,
      assignedAgentId: greenAgent.id,
      resolvedAt: new Date(Date.now() - 1000 * 60 * 60 * 20),
    },
    {
      subject: "Gift wrapping option missing at checkout",
      description: "I want to add gift wrapping to my order but the option that's usually on the cart page isn't showing up anymore. Did you remove it? It's listed as a feature on the product page.",
      status: TicketStatus.CLOSED,
      priority: Priority.LOW,
      channel: Channel.CHAT,
      tags: ["gift-wrapping", "checkout", "ux"],
      aiSuggestedResponse: "Hi Rafael, the gift wrapping option was temporarily hidden during a checkout redesign that launched this week. We've now re-added it — you'll find it on the cart page under 'Add a personal touch.' The option includes our recycled kraft paper wrapping with a handwritten card. It's available for all orders except large/bulky items. Sorry for the confusion during the transition!",
      aiPriority: Priority.LOW,
      aiAnalyzedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5),
      customerId: rafael.id,
      assignedAgentId: greenAgent.id,
      resolvedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4),
    },
    {
      subject: "Account merge request after email change",
      description: "I recently changed my email address from mei.lin.old@gmail.com to mei@ecobasket.sg. I now have two separate accounts and my order history and loyalty points are split. Can these be merged?",
      status: TicketStatus.CLOSED,
      priority: Priority.LOW,
      channel: Channel.EMAIL,
      tags: ["account", "merge", "email-change"],
      aiSuggestedResponse: "Hi Mei, I've merged both accounts into your primary account (mei@ecobasket.sg). All 23 orders and 430 loyalty points from your old account have been transferred. Your new account now shows your full purchase history dating back to 2023. The old account (mei.lin.old@gmail.com) has been deactivated. If you notice anything missing, please reply and I'll investigate. As a thank-you for your patience during this, I've added 50 bonus points to your balance.",
      aiPriority: Priority.LOW,
      aiAnalyzedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 6),
      customerId: mei.id,
      assignedAgentId: greenAgent.id,
      resolvedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5),
    },
  ]

  for (const t of greenTickets) {
    await prisma.ticket.create({ data: { ...t, tenantId: greenleaf.id } })
  }

  const totalTickets = auraTickets.length + pixelTickets.length + greenTickets.length

  console.log(`\n✅ Seed complete!`)
  console.log(`   Tenants:  3 (Aura Logistics, Pixel Stream, GreenLeaf Retail)`)
  console.log(`   Tickets:  ${totalTickets}`)
  console.log(`   Customers: ${auraCustomers.length + 4 + 5}`)
  console.log(`\n⚠️  DEMO LOGIN SETUP:`)
  console.log(`   1. Go to clerk.com → your app → Users → Create user`)
  console.log(`      Email: demo@aura-logistics.com`)
  console.log(`      Password: (set a strong password)`)
  console.log(`   2. Copy the User ID (starts with 'user_...')`)
  console.log(`   3. Add to .env: DEMO_CLERK_USER_ID=user_xxxxxxxxxx`)
  console.log(`   4. Re-run: pnpm db:seed`)
  console.log(`   5. Set DEMO_CLERK_USER_ID in your Vercel/deployment env vars too`)
}

main()
  .catch((e) => {
    console.error("❌ Seed failed:", e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
    await pool.end()
  })
